name: dc_datatable
description: Widget Datatable with pagination
version: 1.0.0
homepage: https://github.com/ddbits/dc_datatable.git


environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider:  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
